apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sru-portal-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: portal.sru.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sru-portal-backend-svc
                port:
                  number: 80
