apiVersion: v1
kind: Secret
metadata:
  name: sru-portal-secret
type: Opaque
stringData:
  JWT_ACCESS_SECRET: "change_me"
  JWT_REFRESH_SECRET: "change_me"
  SESSION_SECRET: "change_me"
  SMTP_USER: "smtp_user"
  SMTP_PASS: "smtp_pass"
  WHATSAPP_API_KEY: "placeholder"
