name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-images:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build backend image
      run: docker build -f backend/Dockerfile -t sraap-backend:$(date +%s) backend
    - name: Build frontend image
      run: docker build -f frontend/Dockerfile -t sraap-frontend:$(date +%s) frontend
